# Generated by Django 5.0.3 on 2024-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('docs', 'Docs'), ('txt', 'Plain Text')], max_length=4)),
                ('book_file', models.FileField(upload_to='books/')),
            ],
            options={
                'verbose_name_plural': 'Add books file in various format',
            },
        ),
    ]
